/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 cooling-remesh.glb --keepmaterials --t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    TOP_FRAME: THREE.Mesh
    ['tube^20231023_water_tank001']: THREE.Mesh
    ['tube^20231023_water_tank002']: THREE.Mesh
    ['00_1_1_1_1_1_1_1_1_1_1_1^複製_of_00_cjsv3_all_0424(2)_c33002']: THREE.Mesh
    ['00_1_1_1_1_1_1_1_1_1_1_1^複製_of_00_cjsv3_all_0424(2)_c33']: THREE.Mesh
    ['EK-6-500_13_1_12_1_1_1_1_1_1__1^00_ASM_8_ASM_1_ASM_6_AS_e9b002']: THREE.Mesh
    ['EK-6-500_13_1_12_1_1_1_1_1_1__1^00_ASM_8_ASM_1_ASM_6_AS_e9b']: THREE.Mesh
    FRAME: THREE.Mesh
    GLASS: THREE.Mesh
    GRADIENT: THREE.Mesh
    ['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製_of_00_cjsv3_al_a69002']: THREE.Mesh
    ['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製_of_00_cjsv3_al_a69003']: THREE.Mesh
    ['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製_of_00_cjsv3_al_a69004']: THREE.Mesh
  }
  materials: {
    ['Paint Metallic Black #8.018']: THREE.MeshStandardMaterial
    ['RealCloth Basket Twill Dark Grey #1.001']: THREE.MeshStandardMaterial
    ['Hard Shiny Plastic Black #1.001']: THREE.MeshStandardMaterial
    ['Hard Shiny Plastic Black #1']: THREE.MeshStandardMaterial
    ['Hard Rough Plastic Black #1.001']: THREE.MeshStandardMaterial
    ['Hard Rough Plastic Black #1']: THREE.MeshStandardMaterial
    ['Paint Metallic Black #8.016']: THREE.MeshStandardMaterial
    ['Plastic Polypropylene Rough 3mm #1.001']: THREE.MeshStandardMaterial
    ['DDR4-RAM:color:20:56:176 #1.004']: THREE.MeshStandardMaterial
    ['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製 of 00_cjsv3_al_674cdfc']: THREE.MeshStandardMaterial
    ['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製 of 00_cjsv3_al_674']: THREE.MeshStandardMaterial
    ['Plastic Polypropylene Rough 3mm #1']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Cooling(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d/y70/cooling-remesh.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TOP_FRAME.geometry} material={materials['Paint Metallic Black #8.018']} position={[-0.039, 0.459, 0.161]} rotation={[-Math.PI, 0, 0]} scale={[-0.059, -0.014, -0.011]} />
      <mesh geometry={nodes['tube^20231023_water_tank001'].geometry} material={materials['RealCloth Basket Twill Dark Grey #1.001']} position={[-0.038, 0.477, 0.093]} rotation={[0, 0, Math.PI]} scale={0.001} />
      <mesh geometry={nodes['tube^20231023_water_tank002'].geometry} material={materials['RealCloth Basket Twill Dark Grey #1.001']} position={[-0.038, 0.477, 0.093]} rotation={[0, 0, Math.PI]} scale={0.001} />
      <mesh geometry={nodes['00_1_1_1_1_1_1_1_1_1_1_1^複製_of_00_cjsv3_all_0424(2)_c33002'].geometry} material={materials['Hard Shiny Plastic Black #1.001']} position={[0.018, 0.251, -0.107]} rotation={[Math.PI, 1.085, 0]} scale={0.001} />
      <mesh geometry={nodes['00_1_1_1_1_1_1_1_1_1_1_1^複製_of_00_cjsv3_all_0424(2)_c33'].geometry} material={materials['Hard Shiny Plastic Black #1']} position={[0.018, 0.251, -0.08]} rotation={[-Math.PI, 1.085, -0.429]} scale={0.001} />
      <mesh geometry={nodes['EK-6-500_13_1_12_1_1_1_1_1_1__1^00_ASM_8_ASM_1_ASM_6_AS_e9b002'].geometry} material={materials['Hard Rough Plastic Black #1.001']} position={[-0.006, 0.192, -0.094]} rotation={[Math.PI / 2, 0, -0.486]} scale={0.001} />
      <mesh geometry={nodes['EK-6-500_13_1_12_1_1_1_1_1_1__1^00_ASM_8_ASM_1_ASM_6_AS_e9b'].geometry} material={materials['Hard Rough Plastic Black #1']} position={[-0.006, 0.192, -0.067]} rotation={[Math.PI / 2, 0, -0.486]} scale={0.001} />
      <mesh geometry={nodes.FRAME.geometry} material={materials['Paint Metallic Black #8.016']} position={[0.058, 0.29, -0.079]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.GLASS.geometry} material={materials['Plastic Polypropylene Rough 3mm #1.001']} position={[0.058, 0.29, -0.079]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes.GRADIENT.geometry} material={materials['DDR4-RAM:color:20:56:176 #1.004']} position={[0.058, 0.29, -0.079]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製_of_00_cjsv3_al_a69002'].geometry} material={materials['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製 of 00_cjsv3_al_674cdfc']} position={[0.058, 0.29, -0.079]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製_of_00_cjsv3_al_a69003'].geometry} material={materials['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製 of 00_cjsv3_al_674']} position={[0.058, 0.29, -0.079]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
      <mesh geometry={nodes['ICC00_43_1^ICC00_43_ASM_ICC00_ASM_複製_of_00_cjsv3_al_a69004'].geometry} material={materials['Plastic Polypropylene Rough 3mm #1']} position={[0.058, 0.29, -0.079]} rotation={[Math.PI, 1.571, 0]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/cooling-remesh.glb')
